"""Architecture gate enforcement rules."""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

# Project root is resolved relative to this file's location
PROJECT_ROOT = Path(__file__).resolve().parents[5]

COMPONENTS = {
    "backend": PROJECT_ROOT / "backend",
    "frontend": PROJECT_ROOT / "frontend",
    "mobile": PROJECT_ROOT / "mobile",
    "pipeline_runner": PROJECT_ROOT / "tools" / "pipeline_runner",
    "cli": PROJECT_ROOT / "cli",
}

LOCK_FILES = {
    "backend": "mix.lock",
    "frontend": "package-lock.json",
    "mobile": "pubspec.lock",
    "pipeline_runner": "poetry.lock",
    "cli": "mix.lock",
}


@dataclass
class RuleResult:
    """Result of an architecture rule check."""

    rule: str
    passed: bool
    message: str


def check_adr_index() -> RuleResult:
    """Verify all ADR files are listed in the ADR index."""
    adr_dir = PROJECT_ROOT / "docs" / "adr"
    index_path = adr_dir / "README.md"

    if not index_path.exists():
        return RuleResult(rule="adr-index", passed=False, message="docs/adr/README.md not found")

    index_content = index_path.read_text()
    adr_files = sorted(adr_dir.glob("[0-9]*.md"))
    missing = []

    for adr_file in adr_files:
        if adr_file.name not in index_content:
            missing.append(adr_file.name)

    if missing:
        return RuleResult(
            rule="adr-index",
            passed=False,
            message=f"ADR files not in index: {', '.join(missing)}",
        )

    return RuleResult(rule="adr-index", passed=True, message="All ADRs indexed")


def check_component_specs() -> RuleResult:
    """Verify each component has a spec/README.md."""
    missing = []

    for name, path in COMPONENTS.items():
        spec_path = path / "spec" / "README.md"
        if not spec_path.exists():
            missing.append(name)

    if missing:
        return RuleResult(
            rule="component-spec",
            passed=False,
            message=f"Missing spec/README.md: {', '.join(missing)}",
        )

    return RuleResult(rule="component-spec", passed=True, message="All components have specs")


def check_no_cross_imports() -> RuleResult:
    """Verify components do not import from each other directly."""
    violations: list[str] = []
    component_names = list(COMPONENTS.keys())

    for name, path in COMPONENTS.items():
        other_components = [c for c in component_names if c != name]

        for source_file in path.rglob("*"):
            if source_file.is_dir() or source_file.suffix not in {
                ".ex",
                ".exs",
                ".ts",
                ".vue",
                ".dart",
                ".py",
            }:
                continue

            # Skip spec files and lock files
            if "spec/" in str(source_file) or source_file.name.endswith(".lock"):
                continue

            try:
                content = source_file.read_text()
            except (OSError, UnicodeDecodeError):
                continue

            for other in other_components:
                # Check for direct path imports to sibling components
                pattern = rf"(?:import|require|from)\s+.*['\"].*\.\./{other}/"
                if re.search(pattern, content):
                    rel_path = source_file.relative_to(PROJECT_ROOT)
                    violations.append(f"{rel_path} imports from {other}")

    if violations:
        return RuleResult(
            rule="no-cross-imports",
            passed=False,
            message=f"Cross-component imports: {'; '.join(violations[:5])}",
        )

    return RuleResult(rule="no-cross-imports", passed=True, message="No cross-imports detected")


def check_lock_files() -> RuleResult:
    """Verify lock files are committed for components that have run setup.

    Lock files are generated by each component's setup command (mix deps.get,
    npm ci, flutter pub get, poetry install). Missing lock files are reported
    as warnings if the component has a manifest but hasn't been set up yet.
    """
    missing = []

    for name, lock_file in LOCK_FILES.items():
        path = COMPONENTS[name] / lock_file
        if not path.exists():
            missing.append(f"{name}/{lock_file}")

    if missing:
        logger.warning("Missing lock files (run component setup): %s", ", ".join(missing))
        return RuleResult(
            rule="lock-files",
            passed=True,
            message=f"Warning: missing lock files (run setup): {', '.join(missing)}",
        )

    return RuleResult(rule="lock-files", passed=True, message="All lock files present")


def check_coverage_config() -> RuleResult:
    """Verify coverage thresholds are configured in each component."""
    issues = []

    # Backend: check mix.exs for test_coverage
    mix_exs = COMPONENTS["backend"] / "mix.exs"
    if mix_exs.exists():
        content = mix_exs.read_text()
        if "test_coverage" not in content:
            issues.append("backend/mix.exs missing test_coverage config")

    # Frontend: check vite.config.ts for coverage config
    vite_config = COMPONENTS["frontend"] / "vite.config.ts"
    if vite_config.exists():
        content = vite_config.read_text()
        if "coverage" not in content:
            issues.append("frontend/vite.config.ts missing coverage config")

    # Pipeline runner: check pyproject.toml for coverage config
    pyproject = COMPONENTS["pipeline_runner"] / "pyproject.toml"
    if pyproject.exists():
        content = pyproject.read_text()
        if "fail_under" not in content:
            issues.append("pipeline_runner/pyproject.toml missing coverage fail_under")

    # CLI: check mix.exs for test_coverage
    cli_mix_exs = COMPONENTS["cli"] / "mix.exs"
    if cli_mix_exs.exists():
        content = cli_mix_exs.read_text()
        if "test_coverage" not in content:
            issues.append("cli/mix.exs missing test_coverage config")

    if issues:
        return RuleResult(
            rule="coverage-config",
            passed=False,
            message="; ".join(issues),
        )

    return RuleResult(rule="coverage-config", passed=True, message="Coverage configured")


def check_docs_config() -> RuleResult:
    """Verify the VitePress docs site configuration exists."""
    docs_package = PROJECT_ROOT / "docs" / "package.json"

    if not docs_package.exists():
        return RuleResult(
            rule="docs-config",
            passed=False,
            message="docs/package.json not found — VitePress site not configured",
        )

    return RuleResult(rule="docs-config", passed=True, message="docs/package.json present")


RULES = [
    check_adr_index,
    check_component_specs,
    check_no_cross_imports,
    check_lock_files,
    check_coverage_config,
    check_docs_config,
]


def run_all_rules() -> list[RuleResult]:
    """Run all architecture gate rules and return results."""
    results = []
    for rule_fn in RULES:
        result = rule_fn()
        status = "PASS" if result.passed else "FAIL"
        logger.info("[%s] %s — %s", status, result.rule, result.message)
        results.append(result)
    return results
